# 00. Pytorch Functionals


In [2]:
!nvidia-smi

Tue Jul  2 17:57:35 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


In [7]:
print("I'm exite to learn pytorch")

I'm exite to learn pytorch


## Introduction to Tensors
Creating tensor   [Data representation of deep learning in tensor]

### scaler tensor

In [9]:
scaler = torch.tensor(10)
scaler

tensor(10)

In [10]:
scaler.ndim

0

In [11]:
scaler.shape

torch.Size([])

In [19]:
# scaler in tensor pytorch
scaler = torch.tensor(10)
print(scaler)
print(scaler.ndim)  # number of dimensions
print(scaler.shape)  # size of each dimension


tensor(10)
0
torch.Size([])


In [20]:
true_scaler = torch.tensor(True)
true_scaler

tensor(True)

In [21]:

false_scaler = torch.tensor(not True)
false_scaler

tensor(False)

### vector

In [24]:
vactor_tensor = torch.tensor([1, 2, 3])
vactor_tensor

tensor([1, 2, 3])

In [25]:
vect = torch.tensor([True, not True, not False])
vect

tensor([ True, False,  True])

In [29]:
# creating a tensor from a numpy array
# 1D tensor
array_tensor = torch.tensor(np.array([1, 2, 3]))
print(array_tensor)
print(array_tensor.ndim)
print(array_tensor.shape)

tensor([1, 2, 3])
1
torch.Size([3])


### Matrix

In [32]:
MATRIX = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
print(MATRIX)
print("Total number of dimensions :",MATRIX.ndim)
print("Total number of shape :",MATRIX.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Total number of dimensions : 2
Total number of shape : torch.Size([3, 3])


### Tensor

In [35]:
Tensor = torch.tensor([[[10, 11, 12],
                        [13, 14, 15],
                        [16, 17, 18]]])
print(Tensor)
print("Total number of dimensions :",Tensor.ndim)
print("Total number of shape :",Tensor.shape)

tensor([[[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
Total number of dimensions : 3
Total number of shape : torch.Size([1, 3, 3])


In [34]:
Tensor.ndim

4

| Name   | What is it? | Number of dimensions | Lower or upper (usually/example) |
|--------|-------------|----------------------|----------------------------------|
| scalar | a single number | 0 | Lower (a) |
| vector | a number with direction (e.g. wind speed with direction) but can also have many other numbers | 1 | Lower (y) |
| matrix | a 2-dimensional array of numbers | 2 | Upper (Q) |
| tensor | an n-dimensional array of numbers; can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector | can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector | Upper (X) |


In [36]:
Tensor[0]

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

### Random Tensors
Random tensors are important because the way many neural networks learn is that
they start with tensors full of random numbers and then adjust those numbers to
better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [46]:
# create a ramdom tensors of shape (3, 4)
random_tensor = torch.rand(5,4)

random_tensor

tensor([[0.1380, 0.0680, 0.8981, 0.4444],
        [0.8465, 0.6610, 0.0560, 0.8718],
        [0.5725, 0.2244, 0.8796, 0.0165],
        [0.2177, 0.7618, 0.1033, 0.0088],
        [0.8110, 0.6547, 0.1401, 0.9855]])

In [47]:
random_tensor.ndim

2

In [48]:
random_tensor.shape

torch.Size([5, 4])

In [50]:
# create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # height ,width ,colour channels
random_image_tensor

tensor([[[0.3873, 0.7824, 0.1394],
         [0.6242, 0.3356, 0.3415],
         [0.5228, 0.1490, 0.7373],
         ...,
         [0.5311, 0.8525, 0.5146],
         [0.6594, 0.0911, 0.2819],
         [0.5394, 0.1532, 0.1808]],

        [[0.0629, 0.6698, 0.3130],
         [0.3835, 0.2439, 0.0657],
         [0.8826, 0.0832, 0.1179],
         ...,
         [0.8495, 0.8988, 0.7709],
         [0.4546, 0.9279, 0.5411],
         [0.9418, 0.8855, 0.3204]],

        [[0.2974, 0.5559, 0.3278],
         [0.7538, 0.8421, 0.3760],
         [0.6700, 0.5882, 0.7476],
         ...,
         [0.8207, 0.9605, 0.1036],
         [0.4967, 0.8635, 0.5215],
         [0.7538, 0.2103, 0.7086]],

        ...,

        [[0.3439, 0.4740, 0.4642],
         [0.3608, 0.8765, 0.9541],
         [0.0155, 0.8607, 0.9659],
         ...,
         [0.9139, 0.6485, 0.6444],
         [0.9753, 0.4669, 0.6109],
         [0.7138, 0.6796, 0.4227]],

        [[0.6881, 0.4042, 0.8845],
         [0.3153, 0.7421, 0.4551],
         [0.

In [51]:
torch.rand(3, 3)

tensor([[0.5313, 0.1702, 0.4140],
        [0.8962, 0.5868, 0.4402],
        [0.9953, 0.3244, 0.8734]])

### Zeros and Ones

In [53]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [54]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [57]:
zeros * ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [59]:
zeros.dtype, ones.dtype

(torch.float32, torch.float32)